name: 'Manley & Associates'
favicon: null
layout_spectrum: 0.28116
typography_spectrum: 0.22417380078695714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#ffffff'
    - '#cdcabc'
    - '#00eaff'
    - '#484933'
  brandStrength: 0.4375
  lightness: 0.772275966592133
  saturation: 0.6515631431248039
  rhythmicContrast: 0.9938332848250866
purpose: []
